### ISSUE TITLE
如何製作留言板?

### ISSUE THREAD

**Issue by jinglunT** [jinglunT/model#7]

**Comment by bestian** [comment]
手動寫留言板比較複雜
用現成的Facebook留言板比較簡單~

**Comment by bestian** [comment]
這邊有FB的說明文
https://developers.facebook.com/docs/plugins/embedded-comments/?translation

**Comment by bestian** [comment]
如果你要走難的路也行，用firebase可以架
我可以幫你架初步程式碼

**Comment by bestian** [comment]
https://console.firebase.google.com/?gclid=Cj0KCQjw3qzzBRDnARIsAECmryorRs3dMhpfqAlE1XF06Y4E3komfpmIu0ocg55CiDeZoKSkLnw2EV8aAoAOEALw_wcB

**Comment by jinglunT** [comment]
嘗試以fb身分留言

**Comment by bestian** [comment]
這部份比較難, 可以再查
